// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ForceReset():Promise<string>;

export function GetConfig():Promise<main.SitLongConfig>;

export function GetRemainingTime():Promise<number>;

export function PauseTimer():Promise<void>;

export function ResetTimer():Promise<void>;

export function SetActivateOnTimer(arg1:boolean):Promise<void>;

export function SetInterval(arg1:number):Promise<void>;

export function SetMessage(arg1:string):Promise<void>;

export function SetNotificationDuration(arg1:number):Promise<void>;

export function SetShortcut(arg1:main.ShortcutConfig):Promise<void>;

export function StartTimer():Promise<void>;

export function TestOneMinute():Promise<string>;

export function TestTimer():Promise<string>;
