// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceReset() {
  return window['go']['main']['App']['ForceReset']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRemainingTime() {
  return window['go']['main']['App']['GetRemainingTime']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function SetActivateOnTimer(arg1) {
  return window['go']['main']['App']['SetActivateOnTimer'](arg1);
}

export function SetInterval(arg1) {
  return window['go']['main']['App']['SetInterval'](arg1);
}

export function SetMessage(arg1) {
  return window['go']['main']['App']['SetMessage'](arg1);
}

export function SetNotificationDuration(arg1) {
  return window['go']['main']['App']['SetNotificationDuration'](arg1);
}

export function SetShortcut(arg1) {
  return window['go']['main']['App']['SetShortcut'](arg1);
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function TestOneMinute() {
  return window['go']['main']['App']['TestOneMinute']();
}

export function TestTimer() {
  return window['go']['main']['App']['TestTimer']();
}
